# Generated by Django 2.1 on 2018-08-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_product_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.FloatField(default=0, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.FloatField(default=0, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='购买次数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='视频地址'),
        ),
    ]
