# Generated by Django 2.1 on 2018-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20180815_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顺序'),
        ),
    ]
