# Generated by Django 2.1 on 2018-08-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20180815_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Property'),
        ),
    ]
