# Generated by Django 2.1 on 2018-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20180815_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_enable',
            field=models.BooleanField(default=False, verbose_name='横幅显示？'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hot',
            field=models.PositiveIntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='详情图片'),
        ),
    ]
