# Generated by Django 2.1 on 2018-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20180815_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.PositiveIntegerField(default=200, verbose_name='Score'),
        ),
    ]
