# Generated by Django 2.1 on 2018-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='渲染内容'),
        ),
    ]
