# Generated by Django 2.1 on 2018-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='视频ID'),
        ),
    ]
