# Generated by Django 2.1 on 2018-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_product_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id'], 'verbose_name': '配置', 'verbose_name_plural': '配置'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
