# Generated by Django 2.1 on 2018-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_auto_20180816_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='code',
        ),
        migrations.AddField(
            model_name='member',
            name='open_id',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='开放ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='标识'),
            preserve_default=False,
        ),
    ]
