# Generated by Django 2.1 on 2018-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_auto_20180816_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='国家'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='language',
            field=models.CharField(default=1, max_length=100, verbose_name='语言'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.URLField(verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='province',
            field=models.URLField(max_length=500, verbose_name='省份'),
        ),
    ]
