# Generated by Django 2.1 on 2018-08-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_auto_20180816_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province_name',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mall.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.District'),
        ),
        migrations.AddField(
            model_name='address',
            name='provice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mall.Province'),
            preserve_default=False,
        ),
    ]
