# Generated by Django 2.1 on 2018-08-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_auto_20180817_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id'], 'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
    ]
