# Generated by Django 2.1 on 2018-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_auto_20180820_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_time',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
