# Generated by Django 2.1 on 2018-08-20 12:00

import acmin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_auto_20180820_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0, verbose_name='状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Order')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'ordering': ['-id'],
            },
            bases=(acmin.models.AcminModel, models.Model),
        ),
    ]
