# Generated by Django 2.1 on 2018-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0021_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='订单号'),
            preserve_default=False,
        ),
    ]
