# Generated by Django 2.1 on 2018-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_order_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_fee',
            field=models.PositiveIntegerField(default=10, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已取消')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已取消')], default=0, verbose_name='状态'),
        ),
    ]
