# Generated by Django 2.1 on 2018-08-20 14:42

import acmin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_auto_20180820_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tracking_number', models.CharField(max_length=30, verbose_name='物流单号')),
                ('fee', models.PositiveIntegerField(verbose_name='费用')),
            ],
            options={
                'verbose_name': '物流',
                'verbose_name_plural': '物流',
                'ordering': ['-id'],
            },
            bases=(acmin.models.AcminModel, models.Model),
        ),
        migrations.CreateModel(
            name='LogisticsTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.CharField(max_length=500, verbose_name='事件')),
                ('event_time', models.DateTimeField(verbose_name='时间')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Logistics')),
            ],
            options={
                'verbose_name': '物流跟踪',
                'verbose_name_plural': '物流跟踪',
                'ordering': ['-id'],
            },
            bases=(acmin.models.AcminModel, models.Model),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '物流公司',
                'verbose_name_plural': '物流公司',
                'ordering': ['-id'],
            },
            bases=(acmin.models.AcminModel, models.Model),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='provice',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Address'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Shipper'),
        ),
    ]
