# Generated by Django 2.1 on 2018-08-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0025_auto_20180820_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='address',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='logisticstrace',
            name='logistics',
        ),
        migrations.AddField(
            model_name='logisticstrace',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mall.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='物流单号'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近签到日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='province',
            field=models.CharField(max_length=500, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.DeleteModel(
            name='Logistics',
        ),
    ]
