# Generated by Django 2.1 on 2018-08-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_auto_20180820_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reputation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reputation',
            name='type',
        ),
        migrations.AddField(
            model_name='reputation',
            name='comment',
            field=models.SmallIntegerField(choices=[(2, '好评'), (1, '中评'), (0, '差评')], default=2),
        ),
        migrations.AddField(
            model_name='reputation',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mall.OrderItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Shipper', verbose_name='物流公司'),
        ),
    ]
